-- MySQL Script generated by MySQL Workbench
-- 07/07/19 12:44:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema COPY_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema COPY_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `COPY_DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `COPY_DB` ;

-- -----------------------------------------------------
-- Table `COPY_DB`.`submissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COPY_DB`.`submissions` (
  `id` VARCHAR(30) NOT NULL COMMENT '',
  `title` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COPY_DB`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COPY_DB`.`config` (
  `Debug` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `DebugServer` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  `IntervalTimeInSeconds` INT NOT NULL DEFAULT 100 COMMENT '',
  `MinUpVotes` INT NOT NULL DEFAULT 10 COMMENT '',
  `PostLimit` INT NOT NULL DEFAULT 10 COMMENT '',
  `MessageLimit` INT NOT NULL DEFAULT 2000 COMMENT '',
  `PageSize` INT NOT NULL DEFAULT 10 COMMENT '',
  `CensorMode` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '')
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `COPY_DB`.`sentences` (
  `Id` INT PRIMARY KEY AUTO_INCREMENT,
  `Post_id` LONGTEXT NOT NULL,
  `Sentence` LONGTEXT NOT NULL,
  `Date` BIGINT NOT NULL)
ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE utf8mb4_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
